language: go
go:
  - "1.12.x"
  - "1.13.x"
os:
  - linux
  - osx
go_import_path: fyne.io/fynedesk
gobuild_args: "-v"

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - xorg-dev

before_script:
- go get golang.org/x/tools/cmd/goimports
- go get github.com/fzipp/gocyclo
- go get golang.org/x/lint/golint
- go get github.com/mattn/goveralls
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
- test -z $(goimports -e -d $GO_FILES | tee /dev/stderr)
- go test -v -covermode=atomic -coverprofile=coverage.out ./...
- go vet ./...
- golint -set_exit_status $(go list)
- gocyclo -over 50 $GO_FILES
- export coverage=$(go tool cover -func coverage.out | tail -n 1 | awk '{ print $3 }' | cut -d \% -f 1 | cut -d \. -f 1)
- if [ $coverage -lt 16 ]; then echo "Test coverage lowered"; exit 1; fi
- |
  set -e
  if [[ "$TRAVIS_PULL_REQUEST" == "false" && -n "$COVERALLS_TOKEN" ]]; then
    go test -covermode=atomic -coverprofile=coverage.out ./...
    $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  fi

env:
  matrix:
  - GO111MODULE=on
  global:
  - secure: "HZC8CB83Fdms+QtVWElSsoVoir82TXySg7Fqj0lJPntNFw+NNW40JVxHOeHVIGgUSp4E8POJzMFGQ28Uxw8LU1h6Wrp0owNe5lYXeZrQnL7TSDEanaBt1+yzWPRtfsZpqzzCOmQdUgEqvAs2dxlC5/TpyCdIrOf9SwiUuRGpq5s+oxXF+TJXPVwJ0r9oTFB1pm6opQTKNKKQSxblgsZu1C5/AzwPwXUZdPdhLVA6pXDavagOnUHjEbpYdMYXQkJBnxmZHj0Xx5rrAkJVuU11s/Mng5TBGC9byE29BLRnw3/exu9/Uslv4ziNK9ck3KJ0IxIdV4DDZgPSAnWnUoRFrGIwKefK9f62yJRO2mIrbl0iJV57E6MOJClumz1G+ROW5fqLAyM96GB8aZC9LRiK++j7i0MpyLI43h6HBoOTrKadNn2mK1RrJDeaKvCCigFKEPNvj48yfjY2ksPWDRSFoWkrC/bNTDN2z4gZYea3x0ghEOTmHEBD9xomF4ptWf+vpa+QF5tgy9DFEJ9V8rGHj/IXqx3d5QrFBYPkipjVvlTOUDCUkygivz2Ol4edwitLo4yNl88V+qtBTiWQlaK6ne2+6qNTFjKGux2pPuHHB9ooTkZ0jOf/xUAzk0mj6rTWIaZmuq4ydnN1DfPsalLBZBcIIi575is2eP8F6VADw/w="
