language: go
go:
  - "1.12.x"
  - "1.15.x"
os:
  - linux
  - osx
go_import_path: fyne.io/fynedesk
gobuild_args: "-v"

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - xorg-dev

before_script:
- go get github.com/mattn/goveralls
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
- go test -v -covermode=atomic -coverprofile=coverage.out ./...
- |
  set -eo
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export coverage=$(go tool cover -func coverage.out | tail -n 1 | awk '{ print $3 }' | cut -d \% -f 1 | cut -d \. -f 1)
    echo "Coverage at $coverage"
    if [ $coverage -lt 28 ]; then echo "Test coverage lowered"; exit 1; fi
    if [[ "$TRAVIS_PULL_REQUEST" == "false" && -n "$COVERALLS_TOKEN" ]]; then
      go test -covermode=atomic -coverprofile=coverage.out ./...
      $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    fi
  fi

env:
  matrix:
    - GO111MODULE=on
  global:
    - secure: "EuWo8Pg6ZkcRYtkIc1zIrcEhlOW1RWHG/rQWi767Go8uNEa+WWpAoTr8nrjNym7R2C8z3QBFrPd3PZWioYBsvmM6sm0tF0L3FK6GgfkrQ8dc6T2DJPtwglw9osRNn709sAJfc2SlctU8rHDw1rZP6U/ITMUMxwLY6F/6SMD/N8fxCfNEEstI4Vk56WQAbNGRpX9aWy1DW5+U7EiEoqdzWp5+4zjXfjz4jlBGRx01JX9RdV6vyetqON7+2xZF2oDv60gCgQ7BsWJoP8qZVnPPHgIt3SG3hFfTlsB/m4euqi83XDJh9DBE4JJ9IrbC9MMKj5qNOaQrz7jWOAmpLmGNpxd+ea0UhR6i2b+xofcwh0eFRA3pf70FRxCrYbIo10v3yRd+dReVVUx1YCuYbwkC/nKhoWCtyxvuayw6SIY0BM6pii/4RXEyPvTtFq/WKqrvGI76HJwjcjSrq8GUdDg7Sg4TReWLM4gDIe4gGvn/PkM2vRpPzNBKvk6Kq6G4bun8kMD2r6zlVGDGBaNBZcIgSl/fjW5NMtVG+KQQgn6yEzvbusScbSYtCmfMynP81jA88ey/+p7UenoT2V4xRm+4yxt90OWPzlyB8Cg78ahlOxeXZ39wPVRmR9wsJx8GCfVi/d+W29jkXEFutn5a6kcMLAm6FtBHSiy8xZHBQeuzKEg="
