// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package theme

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/battery.svg
var resourceBatterySvgData []byte
var resourceBatterySvg = &fyne.StaticResource{
	StaticName:    "assets/battery.svg",
	StaticContent: resourceBatterySvgData,
}

//go:embed assets/brightness.sv
//go:embed assets/brightness.svg
var resourceBrightnessSvgData []byte
	StaticName:    "assets/brightness.svg",
	StaticName: "assets/brightness.svg",
	StaticContent: resourceBrightnessSvgData,
/
}
//go:embed assets/broken_image.svg
var resourceBrokenimageSvgData []byte
	StaticName:    "assets/broken_image.svg",
	StaticName: "assets/broken_image.svg",
	StaticContent: resourceBrokenimageSvgData,
b
}
//go:embed assets/calculate.svg
var resourceCalculateSvgData []byte
	StaticName:    "assets/calculate.svg",
	StaticName: "assets/calculate.svg",
	StaticContent: resourceCalculateSvgData,


}
//go:embed assets/display.svg
	StaticName:    "assets/display.svg",
var resourceDisplaySvg = &fyne.StaticResource{
	StaticName: "assets/display.svg",
StaticContent: resourceDisplaySvgData,

	StaticContent: resourceDisplaySvgData,
}
	StaticName:    "assets/ethernet.svg",
var resourceEthernetSvgData []byte
var resourceEthernetSvg = &fyne.StaticResource{
ntent: resourceEthernetSvgData,
}


	StaticName:    "assets/fish_onwhite.png",
	StaticContent: resourceEthernetSvgData,
}
shonwhitePng = &fyne.StaticResourc
//go:embed assets/fish_onwhite.png
var resourceFishonwhitePngData []byte
var resourceFishonwhitePng = &fyne.StaticResource{
	StaticName:    "assets/fyne.png",
	StaticContent: resourceFishonwhitePngData,
}
:    "assets/fyne.png",
	S
//go:embed assets/fyne.png
var resourceFynePngData []byte
	StaticName:    "assets/icon.png",
	StaticName: "assets/fyne.png",
	StaticContent: resourceFynePngData,
/
}
//go:embed assets/icon.png
var resourceIconPngData []byte
	StaticName:    "assets/internet.svg",
	StaticName: "assets/icon.png",
	StaticContent: resourceIconPngData,
t
}
//go:embed assets/internet.svg
var resourceInternetSvgData []byte
	StaticName:    "assets/keyboard.svg",
	StaticName: "assets/internet.svg",
	StaticContent: resourceInternetSvgData,
o
}
//go:embed assets/keyboard.svg
var resourceKeyboardSvgData []byte
	StaticName:    "assets/lock.svg",
	StaticName: "assets/keyboard.svg",
	StaticContent: resourceKeyboardSvgData,
R
}
//go:embed assets/lock.svg
var resourceLockSvgData []byte
	StaticName:    "assets/maximize.svg",
	StaticName: "assets/lock.svg",
	StaticContent: resourceLockSvgData,
e
}
//go:embed assets/maximize.svg
var resourceMaximizeSvgData []byte
	StaticName:    "assets/minimize.svg",
	StaticName: "assets/maximize.svg",
	StaticContent: resourceMaximizeSvgData,
u
}
//go:embed assets/minimize.svg
var resourceMinimizeSvgData []byte
	StaticName:    "assets/mute.svg",
	StaticName: "assets/minimize.svg",
	StaticContent: resourceMinimizeSvgData,
a
}
//go:embed assets/mute.svg
var resourceMuteSvgData []byte
	StaticName:    "assets/person.svg",
	StaticName: "assets/mute.svg",
	StaticContent: resourceMuteSvgData,
D
}
//go:embed assets/person.svg
var resourcePersonSvgData []byte
	StaticName:    "assets/pointer.png",
	StaticName: "assets/person.svg",
	StaticContent: resourcePersonSvgData,
c
}
//go:embed assets/pointer.png
var resourcePointerPngData []byte
	StaticName:    "assets/power.svg",
	StaticName: "assets/pointer.png",
	StaticContent: resourcePointerPngData,


}
//go:embed assets/power.svg
	StaticName:    "assets/sound.svg",
var resourcePowerSvg = &fyne.StaticResource{
	StaticName: "assets/power.svg",
Data,
}

//go:embed assets/sound.svg
	StaticName:    "assets/wifi.svg",
	StaticContent: resourcePowerSvgData,
}
{
	StaticName:    "assets/s
//go:embed assets/sound.svg
var resourceSoundSvgData []byte
	StaticName:    "assets/wifi_off.svg",
	StaticName: "assets/sound.svg",
	StaticContent: resourceSoundSvgData,
}
//go:embed assets/wifi.svg
var resourceWifiSvgData []byte
var resourceWifiSvg = &fyne.StaticResource{
	StaticName: "assets/wifi.svg",
	StaticContent: resourceWifiSvgData,
}
//go:embed assets/wifi_off.svg
var resourceWifioffSvgData []byte
var resourceWifioffSvg = &fyne.StaticResource{
	StaticName: "assets/wifi_off.svg",
	StaticContent: resourceWifioffSvgData,
}
